[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "observa-framework"
version = "0.1.2"
description = "A framework for antipattern detection and observability analysis"
authors = [
  { name = "Anderson Almada", email = "almada@crateus.ufc.br" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "fastapi==0.115.14",
  "uvicorn==0.34.3",
  "pydantic==2.11.7",
  "jinja2==3.1.6",
  "python-dotenv==1.0.1",
  "psycopg2-binary==2.9.9",
  "SQLAlchemy==2.0.41",
  "alembic==1.15.2",
  "PyJWT==2.10.1",
  "pwdlib[argon2]==0.2.1",
  "requests==2.32.3"
]

[project.urls]
Homepage = "https://github.com/andersonalmada/detect-antipatterns"

[tool.setuptools.packages.find]
include = ["observa*"]
exclude = ["data*", "tests*"]